### ISSUE TITLE
Struct Error

### ISSUE THREAD

**Issue by brunchz** [v-p-b/peCloakCapstone#4]
Not sure if I am doing this right, but upon installing all the dependencies, I ran into a problem: 
`Traceback (most recent call last):
  File "peCloak.py", line 1189, in <module>
    main(sys.argv[1:])
  File "peCloak.py", line 1166, in main
    decoder = encode_data(pe, section_to_encode, encoder)
  File "peCloak.py", line 678, in encode_data
    decode_start = struct.pack("<L", section_start + encode_offset)
struct.error: 'L' format requires 0 <= number <= 4294967295
`
Perhaps something wrong with the file read?

**Comment by brunchz** [comment]
I am an idiot, it's because I mistakenly used it on a 64-bit bin...
